#!/bin/bash

# this script extracts the exported symbols of the object files 
# that is listed in the link.txt linker script ($1)
# and saves the output to $2

b=$(for a in $(tr " " "\n" < $1 | grep '.*\.c\.o$'); do 
        readelf -Ws $a 
    done | grep rtapi_exported_ | cut -f3- -d_ | sort -u)

if [ -z "$b" ]; then
    echo -n '{ ' > $2
else
    echo '{ global :' > $2
    for a in $b; do echo $a\; ; done >> $2
fi
echo 'local : * ; };' >> $2
